# Generated by Django 4.0.5 on 2022-06-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0001_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
