# Generated by Django 4.0.5 on 2022-06-24 10:36

import uuid

import django.db.models.deletion
import matching.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[("M", "M"), ("E", "E"), ("I", "I"), ("C", "C"), ("A", "A")],
                max_length=20,
                verbose_name="department",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="grade"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False, verbose_name="is banned"),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("man", "man"), ("woman", "woman"), ("other", "other")],
                max_length=20,
                verbose_name="sex",
            ),
        ),
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=matching.models.user.upload_to, verbose_name="image"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user image",
                "verbose_name_plural": "user images",
            },
        ),
    ]
