# Generated by Django 4.0.5 on 2022-06-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0003_user_department_user_description_user_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "M"),
                    ("E", "E"),
                    ("I", "I"),
                    ("C", "C"),
                    ("A", "A"),
                    ("NULL", ""),
                ],
                max_length=20,
                null=True,
                verbose_name="department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("man", "man"),
                    ("woman", "woman"),
                    ("other", "other"),
                    ("NULL", ""),
                ],
                max_length=20,
                null=True,
                verbose_name="sex",
            ),
        ),
    ]
